### ISSUE TITLE
Deeper Usage Example

### ISSUE THREAD

**Issue by ibrokemypie** [carnager/clerk#24]
Any chance you could outline the workflow you use clerk in, what keybinds, how it integrates with your WM, etc? I'm a bit lost myself, and just ended up binding mod+m to exec clerk...

**Comment by carnager** [comment]
sadly you quit irc, before i could message you. 

Personally I mainly use clerk --add album/latest/track to quickly add/insert/replace songs or albums to/with my playlist. And I use clerk --rate album, but thats only because I use those ratings for some autogenerated html web page.

Most other features (like the excessive playback queue) are more or less a proof of concept and will most likely be simplified/removed soon.
